worker_processes auto;
events { worker_connections 1024; }

rtmp {
    server {
        listen 1935;
        

        chunk_size 32768; 

        application live {
            live on;
            record off;

            meta copy;
            wait_video on;
            on_publish http://control-plane:8080/api/live/publish;
        }
    }
}

http {
    include mime.types;
    default_type application/octet-stream;

    server {
        listen 8080;
        server_name localhost;

        location / {
            root /tmp/hls;
            index index.html;
        }

        location /hls {
            alias /tmp/hls;
            
            # [강제 주입 1] 브라우저가 무조건 HLS로 인식하게 만듦
            types {
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;
            }

            # [강제 주입 2] CORS 허용 (모든 보안 빗장 풀기)
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range' always;
            add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range' always;

            # [강제 주입 3] 캐시 절대 금지
            add_header Cache-Control no-cache;
            expires -1;

            if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Content-Length' 0;
                return 204;
            }
        }
    }
}