worker_processes auto;

events {
    worker_connections 1024;
}

# RTMP 미디어 엔진 설정
rtmp {
    server {
        listen 1935;
        chunk_size 4096;

        application v-live {
            live on;
            record off;
        }
    }
}